### ISSUE TITLE
Settings lower case

### ISSUE THREAD

**Issue by felipeZ** [SCM-NV/qmworks#18]
in the ``Settings`` definition in the [master branch](https://github.com/SCM-NV/qmworks/blob/master/qmworks/settings.py#L30)  we are explicitly converting the name to lower case. While in the [develop branch](https://github.com/SCM-NV/qmworks/blob/develop/qmworks/settings.py#L36) something different is going on. Are we going to inforce the conversation to lower-case or the user should be aware of potential pitfalls due to case-insensitive nature of the Settings?
The [overlay](https://github.com/SCM-NV/qmworks/blob/develop/test/test_overlay.py) test is failing in the develop branch because now if a keyword is upper-case in the template and the user redefines it using lower-case the results are two new branches with the same name but different case.

**Comment by ridderl** [comment]
Michal decided to remove the lowercasing in PLAMS, because it caused some issues. See end of discussion in https://gitlab.pyadf.org/e-science/plams/issues/3. I decided it is best to be consistent with the changes in PLAMS and so changed accordingly in qmworks (development branch). It means the user should be aware of it.
