### ISSUE TITLE
qmworks/__init__

### ISSUE THREAD

**Issue by ridderl** [SCM-NV/qmworks#81]
Is there a reason for explicitly defining the imports in qmworks/__init__.py?
Can't we just import * from all the submodules?

The same question holds for the __init__.py inside the submodules

**Comment by felipeZ** [comment]
Python in general encourages to be explicit rather than implicit. And even though you may in principle use ``import *``, that's is not a good practice because it does not tell us where the functions and classes are coming from.
 Also, unless you annotated all the modules with the ``__all__`` we would import everything from the submodules including other packages that would clutter the namespace and create possible name conflicts.

**Comment by ridderl** [comment]
My main issue is that currently if we add a new function in a submodule we need to adapt the imports and `__all__` lists in 2, often 3 different places, which is a lot of maintenance overkill and may result in inconsistencies. I think it is better to make sure that we define only once what is included in `__all__`.
I see two options:
1. We make sure to define `__all__` in all the "lowest level" files that contain the actual code. Then in `qmworks/__init__.py` we import * directly from the subpackages. This is the way it is done in PLAMS: see https://github.com/SCM-NV/PLAMS/blob/master/src/scm/plams/__init__.py
2. We define the `__all__` only in `qmworks/__init__.py` and not in the low level python files. This is the way it is done in Noodles.
